development:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  messages_type: 'Array'

test:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  messages_type: 'string'

production:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  messages_type: 'string'