'欢迎语': '=====美型公告=====

        欢迎来到美型
        让健身运动更快乐！

        在这里可以：
        ① 认识身边靓男美女
        ② 获得专业健身知识
        ③ 抢购健身场馆课程
        ④ 参与热门丰富活动



        =====美型小编====='
'消课': '您的%s课程,已消一课时,课单号%s,上课后别忘记秀成果哦'
'订单': '学员%s购买了您的%s课程，订单编号%s，赶紧登陆去查看订单，别忘记联系学员哦！'